version: '3'
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - /home/pi/grafana:/var/lib/grafana

  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - /home/pi/influxdb:/var/lib/influxdb
